# Generated by Django 2.1.5 on 2022-03-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0002_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='word',
            field=models.CharField(max_length=12),
        ),
    ]
