# Generated by Django 2.1.5 on 2022-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0003_auto_20220317_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='average_guesses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
