# Generated by Django 2.1.5 on 2022-03-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0004_auto_20220307_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='correct_rate',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='time_cost',
        ),
        migrations.AddField(
            model_name='statistics',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='win_streak',
            field=models.IntegerField(default=0),
        ),
    ]
