# Generated by Django 2.1.5 on 2022-03-07 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0005_auto_20220307_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='challengeID',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='challengeID',
        ),
        migrations.AddField(
            model_name='game',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wordgame.Challenge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='word',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
